-- CreateTable
CREATE TABLE `DefaultAccount` (
    `id` VARCHAR(191) NOT NULL,
    `accountId` VARCHAR(191) NOT NULL,
    `companyId` VARCHAR(191) NOT NULL,
    `category` ENUM('PERSEDIAAN', 'PENJUALAN', 'RETUR_PENJUALAN', 'DISKON_PENJUALAN', 'PEMBAYARAN_PENJUALAN', 'PEMBELIAN', 'RETUR_PEMBELIAN', 'DISKON_PEMBELIAN', 'PEMBAYARAN_PEMBELIAN', 'PAJAK_PENGHASILAN', 'LABA_DITAHAN', 'EKUITAS') NOT NULL,
    `deleted` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `DefaultAccount_accountId_key`(`accountId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DefaultAccount` ADD CONSTRAINT `DefaultAccount_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `Account`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DefaultAccount` ADD CONSTRAINT `DefaultAccount_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
