version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_test_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Properly reference the named volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: # Define the named volume here
