/*
  Warnings:

  - The values [PPH_MASUKAN,PPH_KELUARAN] on the enum `TRANSACTION_CATEGORY` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TRANSACTION_CATEGORY_new" AS ENUM ('PERSEDIAAN', 'PENJUALAN', 'RETUR_PENJUALAN', 'PAJAK_DIBAYAR_DIMUKA', 'DISKON_PENJUALAN', 'PEMBAYARAN_PENJUALAN', 'PEMBELIAN', 'RETUR_PEMBELIAN', 'DISKON_PEMBELIAN', 'PEMBAYARAN_PEMBELIAN', 'PAJAK_PENGHASILAN', 'LABA_DITAHAN', 'EKUITAS', 'PIUTANG_USAHA', 'HUTANG_USAHA', 'HPP', 'PPN_MASUKAN', 'PPN_KELUARAN');
ALTER TABLE "DefaultAccount" ALTER COLUMN "category" TYPE "TRANSACTION_CATEGORY_new" USING ("category"::text::"TRANSACTION_CATEGORY_new");
ALTER TYPE "TRANSACTION_CATEGORY" RENAME TO "TRANSACTION_CATEGORY_old";
ALTER TYPE "TRANSACTION_CATEGORY_new" RENAME TO "TRANSACTION_CATEGORY";
DROP TYPE "TRANSACTION_CATEGORY_old";
COMMIT;
