-- AlterTable
ALTER TABLE `DefaultAccount` MODIFY `category` ENUM('PERSEDIAAN', 'PENJUALAN', 'RETUR_PENJUALAN', 'DISKON_PENJUALAN', 'PEMBAYARAN_PENJUALAN', 'PEMBELIAN', 'RETUR_PEMBELIAN', 'DISKON_PEMBELIAN', 'PEMBAYARAN_PEMBELIAN', 'PAJAK_PENGHASILAN', 'LABA_DITAHAN', 'EKUITAS', 'PIUTANG_USAHA', 'HUTANG_USAHA') NOT NULL;
